version: '3.9'
services:
  db:
    image: 'postgis/postgis:15-3.3'
    environment:
      POSTGRES_PASSWORD: 'fskfnskfsdsodksq'
      POSTGRES_DB: 'food-ordering'
    ports:
      - '6428:5432'
    volumes:
      - foodorderingdev:/var/lib/postgresql/data
    command: postgres -c 'max_connections=2500'
volumes:
  foodorderingdev:
    driver: local

#  docker compose -p "foodordering_dev" -f /home/victor/soft/mine/food-ordering/devops/dev/docker-compose.yml up
# docker compose -p "foodordering_dev" -f /home/victor/soft/mine/food-ordering/devops/dev/docker-compose.yml down --remove-orphans --volumes
