version: '3.9'
services:
  db:
    image: 'postgis/postgis:15-3.3'
    environment:
      POSTGRES_PASSWORD: 'fskfnskfsdsodksq'
      POSTGRES_DB: 'food-ordering'
    ports:
      - '6428:5432'
    volumes:
      - foodorderingdev:/var/lib/postgresql/data
    command: postgres -c 'max_connections=2500'

  cache:
    image: redis:7.2.4-alpine3.19
    ports: 
      - '5555:6379'
    command: redis-server --save  20  1 --loglevel warning --requirepass fnfnfnfdnfeddpipweww323
    volumes:  
      - cache:/data
volumes:
  foodorderingdev:
    driver: local
  cache:
    driver: local

